---
- name: Install Docker
  hosts: jenkins-server, sonarqube-server
  become: yes
  become_user: root
  tasks:
  - name: yum update
    yum:
      name: '*'
      state: latest
  
  - name: yum install docker
    yum:
      name: docker
      state: latest

---
- name: Install Docker-compose
  hosts: sonarqube-server
  become: yes
  become_user: root
  tasks:
  - name: yum install pyhton3-pip
    yum:
      name: pip
      state: latest

  - name: Install docker compose
    ansible.builtin.pip:
      name: docker-compose
      state: latest

---
- name: install git
  hosts: jenkins-server, terraform server
  become: yes
  become_user: root
  tasks:
  - name: install git
    ansible.builtin.apt:
      name: git
      state: latest

---
- name: install trivy
  hosts: jenkins-server
  become: yes
  tasks:
  - name: add the trivy repo
    get_url:
      url:  https://github.com/aquasecurity/trivy/releases/download/v0.18.3/trivy_0.18.3_Linux-64bit.deb
      dest: 
  
  - name: install trivy
    ansible.builtin.dpkg_selections:
      name: trivy_0.18.3_Linux-64bit.deb
      selection: install
---

- name: install jenkins
  hosts: jenkins-server, terraform server
  become: yes
  become_user: root
  tasks:
  - name: yum update
    yum:
      name: '*'
      state: latest

  - name: add the jenkins repo
    get_url:
      url:  https://pkg.jenkins.io/redhat-stable/jenkins.repo
      dest: /etc/yum.repos.d/jenkins.repo 

  - name: import a key file from jenkins-ci
    ansible.builtin.rpm_key:
      state: present
      key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key

  - name: yum update
    yum:
      name: '*'
      state: latest

  - name: install java
    shell: amazon-linux-extras install java-openjdk11 -y

  - name: install jenkins
    yum:
      name: jenkins
      state: latest

  - name: start jenkins
    ansible.builtin.systemd:
      enabled: yes
      name: jenkins
      state: started